import Head from 'next/head';

import { Banner } from '../components/banner';
import { Divider } from '../components/divider'

export default function Home() {
  return (
    <div >
      <Head>
        <title>scuba diving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Banner />
      <Divider />
      </main>
    </div>
  );
}
