on:
  pull_request:
    branches:
      - master
      - feature/*
      - story/*
      - release/*

jobs:
  pr-review:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run ESLint
        run: npm run eslint
      - name: Run Prettier
        run: npm run format:check
      - name: Comment on PR
        uses: actions/github-script@0.10.0
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Tests and ESLint have passed!'
            })
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
